services:
  frontend:
    build: ./nalanda-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./nalanda
    ports:
      - "5105:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: webnovel_db
  #   ports:
  #     - "5432:5432"
